#!/bin/bash

backlight="/sys/class/backlight/intel_backlight"

max=`cat ${backlight}/max_brightness`
min=0
step=$(echo $max / 25 | bc)
current=`cat ${backlight}/brightness`
if [[ $1 == "up" ]]
then
  if [[ $current == "1" ]]
  then
    new=$step
  elif [[ $current == "0" ]]
  then
    new=1
  else
    new=$(( $current + $step ))
  fi
elif [[ $1 == "down" ]]
then
  if [[ $current == $step ]]
  then
    new=1
  else
    new=$(( $current - $step ))
  fi
elif [[ $1 == "max" ]]
then
  echo $(( $max / $step ))
  exit 0
else
  echo $(( $current / $step ))
  exit 0
fi

if (( $new > $max ))
then
  new=$max
fi

if (( $new < $min ))
then
  new=$min
fi
if [[ $2 == "-v" ]]
then
  echo "$current > $new"
fi
echo $new > ${backlight}/brightness

pkill -RTMIN+2 i3blocks
