#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
active_sink=$($dir/currentsink)
sinks=($(wpctl status \
           | sed -n '/Sink endpoints\:/q;p' \
           | sed '1,/Sinks\:/d' \
           | head -n-1 \
           | awk '{if ($0 ~ /\*/) {print $3} else {print $2}}' \
           | sed 's/\.//g' \
           | sort -nu
       ))
sinks_len=${#sinks[@]}


if [ -z $1 ]; then

  cur_idx=
  for i in "${!sinks[@]}"; do
    if [[ "${sinks[$i]}" = "${active_sink}" ]]; then
      cur_idx=$i
      break;
    fi
  done

  idx=$cur_idx
  while true; do
    idx=$(( ($idx + 1) % $sinks_len ))
    echo "next index: $idx"
    # break if we've looped all the way around
    if [[ $idx == $cur_idx ]]; then
      echo "tried everything, bye"
      break;
    fi
    next_sink=${sinks[$idx]}
    echo "next sink: $next_sink"
    wpctl set-default $next_sink;
    if [[ $next_sink == $($dir/currentsink) ]]; then
      echo "found the next available sink"
      break;
    fi
    echo "couldn't use this sink"
  done

else

  if echo "$sinks" | grep $1
  then
    sink=$1
  else
    echo "invalid sink"
    exit 0
  fi
fi

pkill -RTMIN+1 i3blocks
