#!/bin/bash

if [[ "$@" ]]
then
  aws sns publish --topic-arn arn:aws:sns:us-east-1:411053564761:tasker --message "$@" --subject "subject" --profile home
else
  aws sns publish --topic-arn arn:aws:sns:us-east-1:411053564761:tasker --message "message" --subject "subject" --profile home
fi
