#!/bin/bash
opacity="ff"
purple1="#${opacity}9b30ff"
purple2="#${opacity}912cee"
purple3="#${opacity}7d26cd"
purple4="#${opacity}551a8b"
grayish="#${opacity}232323"
mediumpurple1="#${opacity}ab82ff"
mediumpurple2="#${opacity}9f79ee"
mediumpurple3="#${opacity}8968cd"
green3="#${opacity}00cd00"
green4="#${opacity}006400"
black="#${opacity}000000"
darkgray="#${opacity}aaaaaa"
white="#${opacity}ffffff"
red="#${opacity}dd1111"
darkorange2="#${opacity}ee7600"

rofi -show run \
 -padding 50 \
 -bw 20 \
 -fullscreen \
 -line-margin 15 \
 -hide-scrollbar \
 -matching fuzzy \
 -columns 1 \
 -font "SourceCodePro 16" \
 -tokenize \
 -color-window "$black, $purple4, $black, $black, $black" \
 -color-normal "$black, $white, $black, $green4, $white" \
 -color-active "$black, $white, $black, $purple4, $white" \
 -color-urgent "$black, $white, $black, $purple4, $white"
