#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$1" ]]; then
  num="$1"
else
  num=$(xrandr | grep -v disconnected | grep connected | wc -l)
fi

mainscreen=eDP-1-1
otherscreen=DP-1-1-2

if [[ "$num" = "2" ]]; then
  xrandr --output $otherscreen --auto --right-of $mainscreen
else
  xrandr --output $otherscreen --off
fi
i3-msg restart
$dir/fixtouchscreen
