#!/usr/bin/env bash
set -e
#outdir="$HOME/screenshots"
outdir="$HOME/reports/"
img="$(uuidgen).png"
out="${outdir}/${img}"
if [[ $1 == "select" ]]; then
  notify-send -a scrot "select area"
  scrot -s $out -e 'xclip -selection c -t image/png < $f'
elif [[ $1 == "window" ]]; then
  scrot -bu $out -e 'xclip -selection c -t image/png < $f'
else
  scrot $out -e 'xclip -selection c -t image/png < $f'
fi
notify-send -a scrot "copied to clipboard"
