#!/usr/bin/env bash
set -e
outdir="$HOME/screenshots"
img="$(uuidgen).png"
out="${outdir}/${img}"
opts="-e 'xclip -selection c -t image/png < $f'"
if [[ $1 == "select" ]]; then
    notify-send -a scrot "select area"
    scrot -s $out $opts
elif [[ $1 == "window" ]]; then
    scrot -bu $out $opts
else
    scrot $out $opts
fi
notify-send -a scrot "copied to clipboard"
