#!/usr/bin/env bash
set -e
outdir="$HOME/screenshots"
user_id=63798244
bukkit="sean-bukkit"
baseurl="https://s3.amazonaws.com/$bukkit/screenshots"
img="$(uuidgen).png"
out="${outdir}/${img}"
if [[ $1 == "select" ]]; then
    notify-send -a scrot "select area"
    scrot -s $out
elif [[ $1 == "window" ]]; then
    scrot -bu $out
else
    scrot $out
fi
aws s3 cp $out "s3://$bukkit/screenshots/" --acl public-read
echo -n "$baseurl/$img" | xclip -i -sel c
notify-send -a scrot "copied to clipboard"
