#!/bin/bash

# Find out whether the touchpad is enabled or not.
tp_enabled=`xinput list-props 13 | grep Device\ Enabled | awk '{ print $4 }'`

if [[ $tp_enabled == 0 ]]
then
    # The touchpad is currently disabled, so turn it on.
    xinput set-prop 13 "Device Enabled" 1
    xinput set-prop 16 "Device Enabled" 1
    xinput set-prop 13 "Synaptics Palm Detection" 1
    xinput set-prop 13 "Synaptics Palm Dimensions" 5, 5
elif [[ $tp_enabled == 1 ]]
then
    # The touchpad is currently enabled, so turn it off.
    xinput set-prop 13 "Device Enabled" 0
    xinput set-prop 16 "Device Enabled" 0
fi
