#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
active_sink=`$dir/currentsink`
current_volume=`pacmd list-sinks |grep -wA 15 'index: '${active_sink}'' |grep 'volume:' |egrep -v 'base volume:' |awk -F : '{print $3}' |grep -o -P '.{0,3}%'|sed s/.$// |tr -d ' '`

good_description=$(pacmd list-sinks \
                     | awk "/index:\ ${active_sink}/{y=1; next}y" \
                     | grep 'alsa\.card_name' \
                     | head -1 \
                     | awk -F = '{print $2}' \
                     | sed -e 's/^[[ ]]*//' \
                     | tr -d '"')

fallback_description=$(pacmd list-sinks \
                         | awk "/index:\ ${active_sink}/{y=1; next}y" \
                         | grep -e 'device.description' \
                         | head -1 \
                         | awk -F = '{print $2}' \
                         | sed -e 's/^[[ ]]*//' \
                         | tr -d '"')

extra_description=$(pacmd list-sinks \
                      | awk "/index:\ ${active_sink}/{y=1; next}y" \
                      | grep -e 'device.profile.description' \
                      | head -1 \
                      | awk -F = '{print $2}' \
                      | sed -e 's/^[[ ]]*//' \
                      | tr -d '"')

if [[ $good_description ]]; then
  current_description=$good_description
else
  current_description=$fallback_description
fi

if [[ $current_description = "WD19 Dock" ]]; then
  current_description="$current_description ($extra_description)"
fi

muted=`pacmd list-sinks |grep -wA 30 'index: '${active_sink}'' | grep 'muted:' | cut -d: -f2 | tr -d ' '`

interval=${2:-5}

if [[ $1 == "up" ]]
then
  [[ $muted == "yes" ]] && pactl set-sink-mute $active_sink toggle && muted="no"
  if [[ $current_volume -lt 125 ]]; then
    pactl set-sink-volume $active_sink "+${interval}%"
  fi
elif [[ $1 == "down" ]]
then
  [[ $muted == "yes" ]] && pactl set-sink-mute $active_sink toggle && muted="no"
  pactl set-sink-volume $active_sink "-${interval}%"
elif [[ $1 == "mute" ]]
then
  pactl set-sink-mute $active_sink toggle
else
  if [[ $muted == "yes" ]]
  then
    volume=""
  else
    volume=""
  fi
  volume="$volume ${current_volume}%"
  if [[ `pactl list sinks short | wc -l` > 1 ]]
  then
    volume="$volume  ${current_description}"
  fi
  echo $volume
fi

pkill -RTMIN+1 i3blocks
