#!/bin/bash

if `service openvpn@sean status | grep running > /dev/null`
then
  action="stop"
else
  action="start"
fi

wlp=$(iw dev | grep wlp | awk '{print $2}')

if [[ $1 == "on" ]]
then
  [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
  service openvpn@sean start
  systemd-resolve --interface $wlp --set-domain none
elif [[ $1 == "off" ]]
then
  [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
  service openvpn@sean stop
  systemd-resolve --interface $wlp --set-domain '~' --set-domain nc.rr.com
elif [[ $1 == "status" ]]
then
  if `service openvpn@sean status | grep running > /dev/null`
  then
    #echo ""
    echo ""
  else
    #echo ""
    echo ""
  fi
else
  [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
  service openvpn@sean $action
fi

pkill -RTMIN+3 i3blocks
