#!/bin/bash

if `service openvpn@sean status | grep running > /dev/null`
then
  running=yes
  action="stop"
else
  running=no
  action="start"
fi

wlp=$(iw dev | grep wlp | awk '{print $2}')

if [[ $1 == "on" ]]; then
  action="start"
elif [[ $1 == "off" ]]; then
  action="stop"
fi

if [[ $1 == "status" ]]
then
  if [[ $running == "yes" ]]
  then
    #echo ""
    echo ""
  else
    #echo ""
    echo ""
  fi
else
  if [[ $action == "start" ]]; then
    [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
    echo turning vpn on
    service openvpn@sean start
  elif [[ $action == "stop" ]]; then
    [ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
    echo turning vpn off
    service openvpn@sean stop
  fi
fi

pkill -RTMIN+3 i3blocks
