#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DOTFILES=$dir/dotfiles
export INSTALLDIR=$HOME

pushd $DOTFILES

echo "creating dirs"

# for d in "$(find * -type d)"; do
#   echo $INSTALLDIR/.$d
#   mkdir -p $INSTALLDIR/.$d
# done

echo "symlinking files"


find * -type f -exec sh -c '
  for f do
    echo "$INSTALLDIR/.$f"
    ln -fns "$DOTFILES/$f" "$INSTALLDIR/.$f"
  done
' exec-sh {} +


popd

echo done
