#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
active_sink=`$dir/currentsink`
current_volume=`pacmd list-sinks |grep -wA 15 'index: '${active_sink}'' |grep 'volume:' |egrep -v 'base volume:' |awk -F : '{print $3}' |grep -o -P '.{0,3}%'|sed s/.$// |tr -d ' '`
current_description=`pacmd list-sinks |grep -wA 30 'index: '${active_sink}'' | grep 'alsa\.name' | awk -F = '{print $2}' | sed -e 's/^[[ ]]*//' | tr -d '"'`

if [[ $1 == "up" ]]
then
    pactl set-sink-volume $active_sink +5%
elif [[ $1 == "down" ]]
then
    pactl set-sink-volume $active_sink -5%
else
    if [[ `pactl list sinks short | wc -l` > 1 ]]
    then
        echo "${current_volume}% (${current_description})"
    else
        echo "${current_volume}%"
    fi
fi
